site_name: Curso WebGIS. Mapas libres con Leaflet y OpenLayers
repo_url: https://github.com/xeoinquedos/curso-webgis/
repo_name: Curso WebGIS
theme:
  name: material
  language: 'es'
markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - markdown_include.include:
      base_path: docs
nav:
  - Home: index.md
  - 1. Creando un mapa: 1_creando_mapa.md
  - 2. El mapa sin datos. A침adir una capa base: 2_capas_base.md
  - 3. Mas all치 de la capa base, a침adiendo mis propios datos: 3_mis_datos.md
  - 4. Y si los datos son enormes: 4_wms_wmts.md
  - 5. Interactuando con el mapa: 5_interactuando_mapa.md
  - 6. Usando OpenStreetMap como fuente de datos, Tilemill. Enlace a GeoTalleres: 6_osm_y_tilemill.md
  - 7. Extra 1. Un visor r치pido con datos vectoriales de OSM usando uMap: 7_extra_1_osm_y_umap.md
